### ISSUE TITLE
When my laptop is fully charged，0.0W appeared

### ISSUE THREAD

**Issue by abolast** [atul-g/plasma-power-monitor#3]
When my laptop is charging, it works well
When my laptop is on battery, it works well
But when my laptop is fully charged and still connected to the power cord, 0.0W appeared
My laptop has a mechanism that stops charging when the battery is fully charged.

**Comment by abolast** [comment]
I couldn't reproduce the 0.0W again, the last time that happened was after my laptop automatically slept(suspend to RAM).
All in all, power-monitor is now working well on my laptop.
So, I will turn off this issus

**Comment by abolast** [comment]
But when I was up from suspend for a small period of time, the 0.0w reappeared. My laptop is fully charged and still connected to the power cord.
I guess this may have a connection with suspend to RAM.
Please forgive me for turning on this issus again

**Comment by atul-g** [comment]
Hi @abolast , sorry for the delay in response as I got caught up with quite a lot of other work!

When laptop is fully charged, it is expected behavior that the power consumed from the battery is 0.0 W as at this state your laptop is completely consuming power from the power-outlet rather than battery. The power-monitor is a very simple widget which collects the Voltage and Current information from `/sys/class/power_supply/BAT[a number]/current_now` and `/sys/class/power_supply/BAT[a number]/voltage_now` which are interface files provided by the kernel. So you can check what the kernel reported usage is by running a `cat` command on the above files (eg: `cat /sys/class/power_supply/BAT1/voltage_now`) when your laptop is fully charged and verify if the power-monitor is functioning properly.
